# -*- coding: utf-8 -*-
"""Data_Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vcT5NF6we9F_kL0J1k7di9Irbkyk92lQ

# Data scapping using Play Store Reviews with Deep Learning

## Importing Libraries
"""

#!pip install google_play_scraper

# ──────────────────────────────────────────────────────────────
# DATA ACQUISITION
from google_play_scraper import reviews_all, Sort
import csv

"""## Data Scrapping"""

# Scrape Facebook app reviews from the US Play Store in English
scrapreview = reviews_all(
    'com.facebook.katana',   # Facebook app ID
    lang='en',               # Language: English
    country='us',            # Country: United States
    sort=Sort.MOST_RELEVANT, # You can also try Sort.NEWEST
    count=10000               # Number of reviews to fetch
)

with open('fb_reviews.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)

    # Get all keys from the first review
    keys = scrapreview[0].keys()
    writer.writerow(keys)  # Write header row once

    # Write each review row
    for review in scrapreview:
        writer.writerow([review.get(key, '') for key in keys])  # Write values for each key